### ISSUE TITLE
Rename num_epoch_per_cycle to num_cycle_per_epoch

### ISSUE THREAD

**Issue by WurmD** [skelemoa/synse-zsl#1]
At https://github.com/skelemoa/synse-zsl/blob/master/synse/README.md and in the code it says

Argument | Possible Values | Description
-- | -- | --
num_epoch_per_cycle | Integer | Number of epochs per cycle 1700 for 5 random and 1900 for others

but in the examples we have: `--num_cycle_per_epoch` 

Please do that refactoring in the code (renaming num_epoch_per_cycle to num_cycle_per_epoch) or revert the change in the examples in the README.md

**Comment by pranaygupta36** [comment]
Thanks for pointing it out, I have corrected the examples in the README.md files.
