### ISSUE TITLE
Confused about some folders

### ISSUE THREAD

**Issue by ruczhouyujie** [skelemoa/synse-zsl#10]
in /synse_resources/ntu_results,what is the different between shift_val_24 and shif_24.
And the test_label in the two folders are not the same.
the labels in shift_val_24 match with the ReadMe,but the other one is not.

**Comment by divyanshusharma1709** [comment]
Hi there @ruczhouyujie! If you'll look at the gating module used for GZSL, you'll see that a seen and an unseen classifier are used in it. The files in the shift_24 folder are the ones required to train the classifier on NTU-120's 96/24 split (for the unseen classifier). The files in shift_val_24 are required to train the seen class classifier. As a heads up, all folders with 'val' in the directory name contain files which are used to train the classifier for seen classes (for use in the gating module).

I hope you now understand why the test_label is not the same in the two folders.

Could you elaborate on the third point? I'm not sure what you meant by it. Feel free to reach out if you need any help!

**Comment by ruczhouyujie** [comment]
Thanks for your reply! I just want to focus on the ZSL(not GZSL), so i need the visual features which are trained only on the seen classes. Could you please tell me where are the zsl features and labels?

**Comment by pranaygupta36** [comment]
Hey, @ruczhouyujie, the seen features can be found in the folders without 'val' in their names. For ex shift_24_r. 
shift_24_r/train.npy contains the train features in the of the samples of the particular split, train_label.npy are the corresponding labels. ztest.npy contains the features for the unseen class samples. The file labels.npy in synse_resources/resources contains the mapping(which index in *_label.npy corresponds to which class).

I hope I was able to clarify.

**Comment by ruczhouyujie** [comment]
> Hey, @ruczhouyujie, the seen features can be found in the folders without 'val' in their names. For ex shift_24_r.
> shift_24_r/train.npy contains the train features in the of the samples of the particular split, train_label.npy are the corresponding labels. ztest.npy contains the features for the unseen class samples. The file labels.npy in synse_resources/resources contains the mapping(which index in *_label.npy corresponds to which class).
> 
> I hope I was able to clarify.

Yes! The test labels are correct in shift_5_r, shift_12_r and shift_10_r .But in shift_24_r, the test labels are [5, 9, 11, 16, 18, 20, 22, 29, 35, 39, 45, 49, 59, 68, 70, 81, 84, 87, 93, 94, 104, 113, 114, 119], which is different from the test labels in ReadMe.md([1, 3, 4 ,10 , 17, 19 , 27, 47, 48, 53, 58, 63, 66, 79, 83, 86, 89, 92, 97, 98, 100, 103, 105, 108]).

**Comment by pranaygupta36** [comment]
Oh you're right it seems we have made an error in the readme. We must have mixed up btw the validation labels and the zero shot test labels. The labels in the shift_24_r folder are correct and I will update the readme accordingly. Thanks for pointing it out.

**Comment by YujieOuO** [comment]
> Oh you're right it seems we have made an error in the readme. We must have mixed up btw the validation labels and the zero shot test labels. The labels in the shift_24_r folder are correct and I will update the readme accordingly. Thanks for pointing it out.

OK,thanks for your reply.It is an interesting work to follow,and could you please release the code to acquire the visual features for ZSL(such as dataloader for seen and unseen classes). I have tried to use shift-gcn, but get a lot of bugs.😂

**Comment by pranaygupta36** [comment]
Hey, I have also used the code from the official 4s shift-gcn repository to obtain the embeddings. I might be able to help you with it if you can email me the error log.

Since (I hope), the issue is resolved, I am closing this. Feel free to reopen or open a new issue if there's something else you need help with.
