### ISSUE TITLE
Extra spaces in examples

### ISSUE THREAD

**Issue by WurmD** [skelemoa/synse-zsl#2]
At https://github.com/skelemoa/synse-zsl/blob/master/synse/README.md there is an extra space at the `dataset` argument and the `ve` argument of each example
`-- dataset 'synse_resources/ntu_results/shift_5_r/' --wdir 'synse_resources/language_modelling/repo_test_synse_5_r' --le bert -- ve`

**Comment by pranaygupta36** [comment]
Thanks for pointing it out, I have updated the respective README files.
