### ISSUE TITLE
[Question] Why did ShiftGCN perform so much better than MS-G3D?

### ISSUE THREAD

**Issue by WurmD** [skelemoa/synse-zsl#3]
Hi,

You performed ablation tests comparing using ShiftGCN vs MS-G3D, and the resulting accuracy drop was striking.

However MS-G3D published results slightly outperform ShiftGCN on the NTU-60 action recognition task.

Do you have thoughts on why ShiftGCN performed so much better in this case? (Was MS-G3D at least faster?)

**Comment by pranaygupta36** [comment]
Yes, even though MS-G3D performs slightly better for recognition on the NTU-60 dataset, I think its the combination of Shift-GCN embeddings with the Sentence-BERT embeddings, which works better for ZSL using our approach. 

The training time is similar for both shift gcn and msg3d embeddings, although msg3d embeddings are slightly higher dimensional.(384 > 256)
