### ISSUE TITLE
How to replicate ablation test with MS-G3D?

### ISSUE THREAD

**Issue by WurmD** [skelemoa/synse-zsl#4]
How to replicate ablation test with MS-G3D?

Running this command:
synse_training.py --ntu=60 --phase=train --ss=5 --st=r --wdir=/home/dario/temp/synse_resources/language_modelling/repo_test_synse_5_r --le=bert --load_classifier --num_cycles=10 --num_epoch_per_cycle=1700 --latent_size=100 --load_epoch=3399 --mode=eval --gpu=0
--dataset=/home/dario/temp/synse_resources/ntu_results/**msg3d**_5_r/ 
--ve=**msg3d** 

yields at
```
def load_models(load_epoch):
    sequence_encoder.load_state_dict(torch.load(se_checkpoint)['state_dict'])
```
```
Exception has occurred: RuntimeError
Error(s) in loading state_dict for Encoder:
	size mismatch for mu_transformation.0.weight: copying a param with shape torch.Size([100, 256]) from checkpoint, the shape in current model is torch.Size([100, 384]).
	size mismatch for logvar_transformation.0.weight: copying a param with shape torch.Size([100, 256]) from checkpoint, the shape in current model is torch.Size([100, 384]).
```
`se_checkpoint == '/home/dario/temp/synse_resources/language_modelling/repo_test_synse_5_r/bert/se_3399.pth.tar'`

**Comment by pranaygupta36** [comment]
The visual feature representation obtained by MSG3D is 384 dimensional, whereas the one obtained by 4s-ShiftGCN is 256 dimensional. The pretrained models currently provided are trained using 4s-ShiftGCN. I can provide the pretrained model with MSG3D embeddings in the next few days, meanwhile you can try to reproduce the results by training synse from scratch using MSG3D embeddings.

**Comment by WurmD** [comment]
That would definetly be helpful, thank you

**Comment by pranaygupta36** [comment]
Hey, please find the trained msg3d model [here](https://iiitaphyd-my.sharepoint.com/:f:/g/personal/pranay_gupta_research_iiit_ac_in/EvFsjjFHaidHiX0TECFGCHUB28G59LQUByqwCVU9de2PVg?e=yr4VNI). 
 
Place the above directory in the `/synse_resources/language_modelling/` directory.

To run the zsl evaluation. 

`python synse_training.py --ntu 60 --phase train --ss 5 --st r --dataset './synse_resources/ntu_results/msg3d_5_r/' --wdir './synse_resources/language_modelling/synse_ms^Cd_5_r' --le bert --ve msg3d --num_cycles 10 --load_classifier --num_epoch_per_cycle 1700 --latent_size 100 --load_epoch 8499 --mode eval --gpu 0`
