### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 27447) exited unexpectedly

### ISSUE THREAD

**Issue by WurmD** [skelemoa/synse-zsl#5]
Hi, I'm yet to train SynSE from scratch because this error keep happening intermittently, but always before reaching epoch 1700, often around 1200. Did it ever happen to you?

`python3 synse_training.py --ntu=60 --phase=train --ss=5 --st=r --dataset=/home/dario/temp/synse_resources/ntu_results/shift_5_r/ --ve=shift --wdir=/home/dario/temp/synse_resources/language_modelling/synse_5_r_retrain --le=bert --mode=train --num_cycles=10 --num_epoch_per_cycle=1700 --latent_size=100 --gpu=0`

at synse/synse_training.py
```
def train_one_cycle(cycle_num, cycle_length):
...
            (inputs, target) = next(iter(train_loader))

```
**RuntimeError: DataLoader worker (pid(s) 27447) exited unexpectedly**

**Comment by divyanshusharma1709** [comment]
Hi @WurmD 
It is possible that you might be running out of memory around the 1200th epoch. How much GPU memory do you have available?

**Comment by WurmD** [comment]
8GB

Usually when that's the case I see an actual RuntimeError: CUDA error: out of memory

I'll go monitor the GPU RAM usage now

**Comment by pranaygupta36** [comment]
The arguments in [lines](https://github.com/skelemoa/synse-zsl/blob/master/synse/synse_training.py#L112-L114) are batch size, num_workers for the dataloader. Maybe you can try reducing the num_workers from 8 and see if it works.
