### ISSUE TITLE
In synse_resources rs10.npy == rs100.npy

### ISSUE THREAD

**Issue by WurmD** [skelemoa/synse-zsl#8]
Just a heads up:

In synse_resources/resources/label_splits rs10.npy is exactly the same as rs100.npy

**Comment by pranaygupta36** [comment]
Hi, Thanks for pointing it out, rs10.npy is actually not required in any of the experiments. I must have made an error while copying the data in the resources folder.

**Comment by divyanshusharma1709** [comment]
Hi! Thanks for the heads up @WurmD ! I'll be closing this issue. Feel free to reopen it if you need to.
